name: bakery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.0.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_image_slideshow: ^0.1.6

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/icons/
   - assets/cakepieces/
   - assets/cupcakes/
   - assets/birthdaycake/
   - assets/muffins/
   
   
   