name: bakery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository: 
    path: packages/authentication_repository
  flow_builder: ^0.0.9
  shared_preferences: ^2.0.13
  introduction_screen:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  formz: ^0.6.0
  go_router: ^10.0.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  provider: ^6.0.5
  firebase_ui_auth: ^1.8.0
  google_fonts: ^4.0.0
  form_inputs: 
    path: packages/form_inputs
  font_awesome_flutter: ^10.1.0
  bloc: ^8.1.2
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_image_slideshow: ^0.1.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/cupcakeicon.png"
    min_sdk_android: 21 #

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/cakepieces/
    - assets/cupcakes/
    - assets/birthdaycake/
    - assets/muffins/
    - assets/weddingcake/