// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB1pvmP6lNc8dI1qRa6KUxzAos_uKI4Hc',
    appId: '1:827002065432:web:efb256ef199ba38b80e96d',
    messagingSenderId: '827002065432',
    projectId: 'login-app-cd0f9',
    authDomain: 'login-app-cd0f9.firebaseapp.com',
    storageBucket: 'login-app-cd0f9.appspot.com',
    measurementId: 'G-H2PE0Z56QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbsYzOQX-1L3jNZr1Z1p8uE3djWLgHjvU',
    appId: '1:827002065432:android:883733502095c47180e96d',
    messagingSenderId: '827002065432',
    projectId: 'login-app-cd0f9',
    storageBucket: 'login-app-cd0f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqG9MqpmEfNYjlIwgvyTOz5dfMqOE-QDE',
    appId: '1:827002065432:ios:183b4f297c2269f680e96d',
    messagingSenderId: '827002065432',
    projectId: 'login-app-cd0f9',
    storageBucket: 'login-app-cd0f9.appspot.com',
    iosBundleId: 'com.example.bakery',
  );
}
